apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghas-compliance
  name: ghas-compliance
  namespace: default
spec:
  selector:
    matchLabels:
      app: ghas-compliance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghas-compliance
    spec:
      containers:
      - image: docker.io/yadhav/ghas-compliance:0.1.0
        name: ghas-compliance
        envFrom:
        - secretRef: 
            name: app-env
        ports:
        - name: http
          containerPort: 3000
      imagePullSecrets:
        - name: regcred
        
