apiVersion: v1
kind: Service
metadata:
  name: svc-ghas-compliance
  labels:
    app: ghas-compliance
spec:
  selector:
    app: ghas-compliance
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer